plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.6'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'com.diffplug.spotless' version '6.25.0'
}

group = 'com.omraty'
version = '0.1.0'
description = 'Omraty backend - Authentification'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-jdbc'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.security:spring-security-crypto'

	implementation("org.flywaydb:flyway-core:11.17.1")
	implementation("org.flywaydb:flyway-database-postgresql:11.17.1")
	runtimeOnly 'org.postgresql:postgresql'

	implementation("io.jsonwebtoken:jjwt-api:0.12.7")
	runtimeOnly("io.jsonwebtoken:jjwt-impl:0.12.7")
	runtimeOnly("io.jsonwebtoken:jjwt-jackson:0.12.7")

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

spotless {
	java {
		target 'src/**/*.java'
		googleJavaFormat('1.17.0').aosp()
		trimTrailingWhitespace()
		endWithNewline()
	}
}

tasks.named('test') {
	useJUnitPlatform()
}
